---
title: "Data cleaning: mortality and gender"
author: "Yini Zhang (yz3005)"
date: "Feb 19th, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##Step 1: Install and load packages
```{r, warning=FALSE, message=FALSE}
# package: dplyr
packages.used="dplyr"

# check packages that need to be installed.
packages.needed=setdiff(packages.used, 
                        intersect(installed.packages()[,1], 
                                  packages.used))
# install additional packages
if(length(packages.needed)>0){
  install.packages(packages.needed, dependencies = TRUE,
                   repos='http://cran.us.r-project.org')
}
library(dplyr)
```

##Step 2: Data cleaning of raw table: CDI.csv
```{r, warning=FALSE, message=FALSE}
# load data and get diseases related to smoking
cdi.raw <- read.csv("../data/CDI.csv")
questions <- levels(cdi.raw$Question)
mortality <- questions[c(12,40,164,193,16,116,117,119,120,122)]

# select columns needed
cdi <- select(cdi.raw, YearStart,LocationAbbr, LocationDesc, Question, DataValueTypeID, DataValue, Stratification1)
cdi <- rename(cdi, year=YearStart, statesAbbr=LocationAbbr, states=LocationDesc, disease=Question, datatype=DataValueTypeID, deathpop=DataValue, class=Stratification1)

# rename the diseases with Abbr.
cdi <- cdi %>%
  mutate(disease = gsub('Mortality from cerebrovascular disease \\(stroke\\)','Cerebrovascular disease', disease),
         disease = gsub('Mortality from coronary heart disease','Coronary heart disease', disease),
         disease = gsub('Mortality from heart failure','Heart failure', disease),
         disease = gsub('Mortality from total cardiovascular disease','Cardiovascular disease', disease),
         disease = gsub('Mortality with chronic obstructive pulmonary disease as underlying or contributing cause among adults aged >=45 years', 'Chronic obstructive pulmonary disease', disease),
         disease = gsub('Arthritis among adults aged >= 18 years','Arthritis', disease),
         disease = gsub('Current asthma prevalence among adults aged >= 18 years','Asthma', disease),
         disease = gsub('Prevalence of chronic obstructive pulmonary disease among adults >= 18','Chronic obstructive pulmonary disease prevalence', disease))
    
# filter the rows we need
cdi.mort <- cdi %>%
  filter(disease=='Cerebrovascular disease'|disease=='Coronary heart disease'| 
         disease=='Heart failure'| disease=='Cardiovascular disease'|disease=='Chronic obstructive pulmonary disease',
         datatype == "Nmbr")

cdi.prev <- cdi %>%
  filter(disease=="Arthritis"|
         disease=="Asthma"|
         disease=="Chronic obstructive pulmonary disease prevalence",
         datatype == "CrdPrev")


# unfactorize the deathpop 
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
cdi.prev$deathpop <- as.numeric.factor(cdi.prev$deathpop)

# add new column ratio to cdi.prev
cdi.prev <- mutate(cdi.prev, 
                     ratio=deathpop)

# unfactorize the deathpop in cdi.mort
cdi.mort$deathpop <- as.numeric.factor(cdi.mort$deathpop)

# filter the dataframe by class
cdi.mort.gender <- filter(cdi.mort, class == "Overall" | class == "Female" | class == "Male")
cdi.prev.gender <- filter(cdi.prev, class == "Overall" | class == "Female" | class == "Male")
```

##Step3: Data cleaning of raw table: population.csv
```{r, warning=FALSE, message=FALSE}
# load population
population <- read.csv("../data/population.csv")
pop <- select(population, NAME, POPESTIMATE2010:POPESTIMATE2014)
pop <- rename(pop, states=NAME, population=POPESTIMATE2010, population=POPESTIMATE2011, population=POPESTIMATE2012,
              population=POPESTIMATE2013, population=POPESTIMATE2014)
pop <- pop[c(1,6:57), ]
```

##Step 4: Merge the two tables
```{r, warning=FALSE, message=FALSE}
# add population to cdi
cdi_2010 <- filter(cdi.mort.gender,year==2010)
cdi_2010_prev <- filter(cdi.prev.gender,year==2010)
pop_2010 <- pop[ ,c(1,2)]
cdi.pop.2010 <- merge(cdi_2010, pop_2010, by.x = "states")
cdi.pop.2010_prev <- merge(cdi_2010_prev, pop_2010, by.x = "states")

cdi_2011 <- filter(cdi.mort.gender,year==2011)
cdi_2011_prev <- filter(cdi.prev.gender,year==2011)
pop_2011 <- pop[ ,c(1,3)]
cdi.pop.2011 <- merge(cdi_2011, pop_2011, by.x = "states")
cdi.pop.2011_prev <- merge(cdi_2011_prev, pop_2011, by.x = "states")

cdi_2012 <- filter(cdi.mort.gender,year==2012)
cdi_2012_prev <- filter(cdi.prev.gender,year==2012)
pop_2012 <- pop[ ,c(1,4)]
cdi.pop.2012 <- merge(cdi_2012, pop_2012, by.x = "states")
cdi.pop.2012_prev <- merge(cdi_2012_prev, pop_2012, by.x = "states")

cdi_2013 <- filter(cdi.mort.gender,year==2013)
cdi_2013_prev <- filter(cdi.prev.gender,year==2013)
pop_2013 <- pop[ ,c(1,5)]
cdi.pop.2013 <- merge(cdi_2013, pop_2013, by.x = "states")
cdi.pop.2013_prev <- merge(cdi_2013_prev, pop_2013, by.x = "states")

cdi_2014 <- filter(cdi.mort.gender,year==2014)
cdi_2014_prev <- filter(cdi.prev.gender,year==2014)
pop_2014 <- pop[ ,c(1,6)]
cdi.pop.2014 <- merge(cdi_2014, pop_2014, by.x = "states")
cdi.pop.2014_prev <- merge(cdi_2014_prev, pop_2014, by.x = "states")

cdi.pop <- rbind(cdi.pop.2010, cdi.pop.2011, cdi.pop.2012, cdi.pop.2013, cdi.pop.2014)
cdi.pop.prev <- rbind(cdi.pop.2010_prev, cdi.pop.2011_prev, cdi.pop.2012_prev, cdi.pop.2013_prev, cdi.pop.2014_prev)

# add a new colum to cdi.pop: the ratio of death among population

cdi.pop.female <- cdi.pop %>%
  filter(class=="Female") %>%
  mutate(population = population * 0.50888) #adjust female population: Female: 50.888%
  
cdi.pop.male <- cdi.pop %>%  
  filter(class=="Male") %>%
  mutate(population = population * 0.49112) #adjust male population: Male: 49.112%

cdi.pop.overall <- filter(cdi.pop, class=="Overall")

cdi.pop <- rbind(cdi.pop.female, cdi.pop.male, cdi.pop.overall)
cdi.pop.mort <- mutate(cdi.pop,
                       ratio = 100*deathpop/population)
```

##Step 5: Get and save national mortality and prevalence in terms of gender
```{r, warning=FALSE, message=FALSE}
# We want to get the national mortality of different gender
# but the raw data here only has the national mortality of overall population

# remove the rows with "United States" in cdi.pop.mort and cdi.pop.prev
# calculate the total national mortality according to gender
cdi.mort.new <- cdi.pop.mort[cdi.pop.mort$states!="United States", ]
cdi.prev.new <- cdi.pop.prev[cdi.pop.prev$states!="United States", ]

national_mortality <- cdi.mort.new %>%
  group_by(year, disease, class) %>%
  select(deathpop, ratio) %>%
  summarise(
    deathtotal = sum(deathpop, na.rm=TRUE),
    ratiototal = sum(ratio, na.rm=TRUE)
  )

# calculate the total national prevalence according to gender
national_prevalence <- cdi.prev.new %>%
  group_by(year, disease, class) %>%
  select(deathpop, ratio) %>%
  summarise(
    deathtotal = sum(deathpop, na.rm=TRUE),
    ratiototal = sum(ratio, na.rm=TRUE)
  )

# write in csv file
write.csv(national_mortality, file = "../output/national_mortality.csv")

# write in csv file
write.csv(national_prevalence, file = "../output/national_prevalence.csv")
```

##Step 5: Get and save state disease prevalence and mortality
```{r, warning=FALSE, message=FALSE}
# save the cleaned state data with disease prevalence
write.csv(cdi.prev.new,file = "../output/states prevalence.csv")

# save the cleaned state data with mortality
write.csv(cdi.mort.new, file = "../output/states mortality.csv")
```


